name: pomodoro
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.12.1
  firebase_storage: ^11.4.1
  firebase_core: ^2.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  mobx_codegen: ^2.1.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
